#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OriginalTestFile {
    pub source: &'static str,
    pub tests: &'static [&'static str],
}

macro_rules! file {
    ($source:literal => [$($test:literal),* $(,)?]) => {
        OriginalTestFile { source: $source, tests: &[$($test),*] }
    };
}

/// Exhaustive catalog of original test methods/cases present on `main` at
/// ef738406b61ad06bae2f402857e464735ab106a2.
///
/// Duplicate names are preserved because they occur in distinct fixture
/// classes in the original source and therefore remain separate obligations.
pub const ORIGINAL_TEST_FILES: &[OriginalTestFile] = &[
    file!("python/destiny/test/ballpark/evolve/test_add.py" => [
        "test_balls_can_not_be_added_during_evolve",
    ]),
    file!("python/destiny/test/ballpark/evolve/test_follow.py" => [
        "test_formation_follow_stopped_ball","test_formation_follow_moving_ball",
        "test_follow_stopped_ball","test_follow_moving_ball",
    ]),
    file!("python/destiny/test/ballpark/evolve/test_goto.py" => [
        "test_goto_direction","test_goto_point",
    ]),
    file!("python/destiny/test/ballpark/evolve/test_iterative_collision.py" => [
        "test_stopped_balls_with_same_location","test_multiple_overlapping_balls",
        "test_stopped_balls_intersecting","test_ball_within_static_ball",
        "test_balls_intersecting_with_goto","test_collision_small_with_massive",
        "test_collision_massive_with_small","test_goto_collision",
        "test_balls_in_warp_should_not_collide","test_non_massive_balls_should_not_collide",
        "test_balls_with_mini_balls_are_collision_targets","test_correct_collision_order",
        "test_substep_collision","test_substep_collision_static","test_collision_from_left",
        "test_collision_from_right","test_collision_from_top","test_collision_from_bottom",
        "test_collision_with_zero_length_capsule","test_collision_at_angle",
        "test_ball_starting_within_cylinder","test_ball_starting_within_sphere",
        "test_ball_with_miniballs_multi_collisions","test_collision_from_left",
        "test_collision_from_right","test_collision_from_top","test_collision_from_bottom",
        "test_collision_from_front","test_collision_from_back","test_collision_at_angle",
        "test_starting_within_box","test_two_aligning_boxes",
    ]),
    file!("python/destiny/test/ballpark/evolve/test_minis.py" => [
        "test_add","test_add","test_add_with_rotation","test_add","test_collide",
        "test_collide_with_miniballs",
    ]),
    file!("python/destiny/test/ballpark/evolve/test_missile.py" => [
        "test_not_aimed_not_massive_from_stationary",
        "test_not_aimed_not_massive_from_moving","test_aimed_not_massive","test_aimed_massive",
    ]),
    file!("python/destiny/test/ballpark/evolve/test_orbit.py" => [
        "test_orbit_ball","test_orbit_stopped_ball_starting_right_distance",
        "test_orbit_stopped_ball_starting_outside","test_orbit_stopped_ball_starting_inside",
        "test_orbit_moving_ball_starting_right_distance",
    ]),
    file!("python/destiny/test/ballpark/evolve/test_simple_collision.py" => [
        "test_stopped_balls_with_same_location","test_stopped_balls_intersecting",
        "test_goto_collision","test_balls_in_warp_should_not_collide",
        "test_collision_from_left","test_collision_from_right","test_collision_from_top",
        "test_collision_from_bottom","test_collision_from_left","test_collision_from_right",
        "test_collision_from_top","test_collision_from_bottom","test_collision_from_front",
        "test_collision_from_back",
    ]),
    file!("python/destiny/test/ballpark/evolve/test_stop.py" => [
        "test_stopped_ball_is_stopped","test_stop_ball_in_goto_mode",
    ]),
    file!("python/destiny/test/ballpark/evolve/test_warp.py" => ["test_warpto"]),
    file!("python/destiny/test/ballpark/test_boxes_and_bubbles.py" => [
        "test_can_initialize_bubbles","test_can_initialize_bubble_for_specific_ball",
        "test_get_ball_ids_in_range_for_ball_id","test_ball_on_edge_of_range_gets_included",
        "test_ignores_out_of_range_balls","test_get_ball_ids_in_range_for_location",
        "test_get_ball_ids_in_range_for_ball_id","test_returns_distance_squared",
        "test_ball_on_edge_of_range","test_ignores_out_of_range_balls",
        "test_get_ball_ids_in_range_for_location","test_source_does_not_exist_raises_runtime_error",
        "test_no_other_ball","test_other_ball_in_triangle","test_other_ball_out_of_range",
        "test_other_ball_on_edge_of_range","test_multiple_balls_in_triangle",
        "test_source_does_not_exist_raises_runtime_error","test_no_other_ball",
        "test_other_ball_in_capsule","test_other_ball_in_capsule_and_on_the_edge_of_one_side",
        "test_other_ball_not_in_capsule_too_far_from_the_edge_of_one_side",
        "test_other_ball_not_in_capsule","test_other_ball_on_edge_of_capsule",
        "test_multiple_balls_in_capsule","test_no_other_ball",
        "test_source_does_not_exist_raises_runtime_error","test_ball_in_cone",
        "test_ball_too_far_away","test_ball_intersects_front_of_cone",
        "test_ball_intersects_cone","test_ball_does_not_intersect_cone","test_box_zero_zero_zero",
        "test_box_zero_zero_one","test_capsule_in_box_zero_zero_zero",
        "test_capsule_in_box_zero_zero_one","test_oriented_box_in_box_zero_zero_zero",
        "test_oriented_box_in_box_zero_zero_one","test_adding_a_capsule_makes_a_box_active",
        "test_adding_a_large_capsule_makes_adjecent_boxes_active",
        "test_adding_a_long_capsule_makes_adjecent_boxes_active",
        "test_returns_none_when_there_are_no_active_boxes",
        "test_returns_list_of_boxes_when_there_are_active_boxes",
        "test_adding_a_box_makes_a_box_active","test_tight_fit","test_level_six",
        "test_intersect_left","test_intersect_right","test_intersect_bottom","test_intersect_top",
        "test_intersect_back","test_intersect_front","test_intersect_top_front_right",
        "test_setting_object_on_existing_box_succeeds",
        "test_setting_object_on_nonexisting_box_fails",
        "test_getting_object_that_has_not_been_set_returns_none",
        "test_can_retrieve_stored_object","test_get_box_on_topmost_level",
        "test_get_bubble_where_none_exists_returns_none","test_get_existing_bubble",
    ]),
    file!("python/destiny/test/ballpark/test_callbacks.py" => [
        "test_callback_gets_called_when_period_has_passed","test_callback_gets_called",
        "test_ignores_balls_that_are_not_free","test_only_interactives_ignores_non_interactive_balls",
        "test_remove_proximity_sensor","test_ball_out_of_range","test_ball_on_edge_of_range",
        "test_leave_proximity","test_detects_ball_in_range_when_in_goto_mode",
        "test_ignores_ball_on_edge_of_range","test_ignores_ball_that_should_be_out_of_range",
        "test_ignores_ball_in_range_if_stopped","test_detects_ball_leaving_range","test_foo",
        "test_detects_target_on_edge_of_range","test_ignores_target_that_should_be_out_of_range",
        "test_detects_target_leaving_range",
        "test_gets_called_when_addminiball_is_called_on_ball_that_is_not_in_park",
        "test_does_not_get_called_when_addminiball_is_called_on_ball_that_is_in_park",
        "test_remove_callback",
    ]),
    file!("python/destiny/test/ballpark/test_getters_and_setters.py" => [
        "test_can_set_ball_mass","test_setting_ball_mass_to_a_negative_value_is_ineffective",
        "test_can_set_ball_radius","test_setting_ball_radius_to_negative_value_is_ineffective",
        "test_can_set_max_speed","test_setting_max_speed_to_negative_value_is_ineffective",
        "test_can_set_ball_position","test_can_set_ball_velocity","test_can_set_speed_fraction",
        "test_setting_speed_fraction_clamps_upper_bound_at_one",
        "test_setting_speed_fraction_clamps_lowe_bound_at_zero","test_can_set_ball_free",
        "test_can_set_ball_massive","test_can_set_ball_global","test_can_set_ball_agility",
        "test_setting_agility_to_negative_value_is_ineffective","test_can_set_ball_interactive",
        "test_setting_ball_velocity_updates_yaw_pitch_and_roll","test_set_boid_true",
        "test_set_boid_false","test_set_ball_troll_no_delay","test_set_ball_troll_with_delay",
        "test_set_ball_rigid","test_can_set_ball_harmonic_not_forcefield",
        "test_can_set_ball_harmonic_make_forcefield",
        "test_can_set_ball_harmonic_remove_forcefield",
        "test_accuracy_is_zero_when_distance_is_zero","test_accuracy_is_zero_when_ball_targets_itself",
        "test_full_accuracy","test_no_falloff","test_some_falloff","test_combination_parameters",
        "test_returns_accuracy_and_tracking_speed_that_we_specify",
        "test_surface_distance_between_two_balls_in_the_same_place_with_no_radius_is_zero",
        "test_surface_distance_between_two_balls_with_no_radius_equals_the_distance_between_the_balls",
        "test_surface_distance_between_two_balls_equals_the_distance_between_the_balls_minus_their_combined_radii",
        "test_euclidean_distance","test_center_distance_between_two_balls_in_the_same_place",
        "test_center_distance_between_two_balls","test_returns_empty_list_when_there_are_none",
        "test_ignores_ball_that_is_not_free","test_finds_following_ball",
        "test_ignores_balls_that_are_not_following","test_ignores_balls_that_are_in_the_same_bubble",
        "test_returns_empty_list_when_there_are_no_followers","test_returns_list_of_followers",
        "test_returns_default_initial_ego_value","test_valid_formation_gets_set",
        "test_formation_out_of_range_does_not_get_set",
        "test_followers_whom_we_no_longer_have_room_for_get_dropped",
    ]),
    file!("python/destiny/test/ballpark/test_lifecycle_management.py" => [
        "test_can_create_ballpark","test_add_ball_creates_a_client_ball",
        "test_add_ball_adds_ball_to_park","test_remove_ball_from_park","test_remove_ball_no_delay",
        "test_remove_ball_with_delay","test_clear_all_removes_ball_from_park",
        "test_addition_of_invalid_ball_id_raises_typeerror","test_addition","test_no_change",
        "test_removal","test_empty_bubble_transitions_list_is_sent_as_empty",
        "test_adding_ball_transitions_it_to_bubble","test_adding_two_balls_transition_them_to_bubble",
        "test_mushroom_gets_created_correctly","test_mushroom_can_not_be_created_with_invalid_owner",
        "test_mushroom_that_is_not_set_free_does_not_expand","test_mushroom_expands_correctly",
        "test_mushrooms_die_when_fully_expanded","test_parameters_get_set_correctly",
        "test_ball_id_gets_generated","test_capsule_id_gets_generated",
        "test_oriented_box_id_gets_generated","test_ball_ids_get_incremented",
        "test_capsule_ids_get_incremented","test_oriented_box_ids_get_incremented",
        "test_ball_and_capsule_ids_share_the_same_id_generator",
    ]),
    file!("python/destiny/test/ballpark/test_movement_controls.py" => [
        "test_follow_ball","test_follow_ball_with_range","test_ball_can_not_follow_self",
        "test_ball_can_not_follow_moribund_ball",
        "test_removing_ball_stops_followers_from_following_that_ball","test_sets_ids_correctly",
        "test_sets_follow_range_as_negative_sum_of_src_and_dst_radii",
        "test_can_not_follow_moribund_ball",
        "test_removing_ball_stops_followers_from_following_that_ball",
        "test_sets_missile_mode_on_src_ball","test_can_warp",
        "test_minrange_and_warpfactor_are_stored_in_strange_places",
        "test_if_warp_location_is_too_close_we_goto_it_instead","test_can_goto","test_go_right",
        "test_go_left","test_go_up","test_go_down","test_go_forward","test_go_backward",
        "test_three_dimensional_movement","test_direction_vector_gets_normalized","test_can_orbit",
        "test_can_not_orbit_self","test_orbit_at_range","test_can_not_orbit_at_nan_range",
        "test_can_not_orbit_cloaked_ball","test_can_not_orbit_ball_in_different_bubble",
        "test_stop_stopped_ball","test_stop_following_ball","test_stop_orbiting_ball",
        "test_stop_missile","test_stop_ball_in_formation","test_src_gets_launched_at_dst",
        "test_owner_of_missile_is_correct","test_massive_missile",
        "test_direction_of_non_aimed_missiles",
        "test_additional_velocity_of_missile_is_the_same_as_the_max_velocity_of_its_owner_if_above_limit",
        "test_initial_velocity_of_owner_has_impact_of_non_aimed_missile_direction_and_speed",
        "test_direction_of_aimed_missiles","test_can_follow_in_formation","test_warps_immediately",
        "test_velocity_is_approximately_one_au","test_ball_in_goto_mode_does_not_warp",
    ]),
    file!("python/destiny/test/ballpark/test_stream_read_write.py" => [
        "test_write_no_ball","test_write_ball_then_read_ball","test_write_read_miniball",
        "test_write_read_minicapsule","test_write_read_minibox","test_write_no_ball",
        "test_write_ball_then_read_ball",
    ]),
    file!("python/destiny/test/ballpark/test_time.py" => [
        "test_ballpark_time_initialises_to_zero","test_adjust_times_adds_to_ballpark_time",
        "test_initial_state_is_paused","test_can_start","test_can_pause",
    ]),
    file!("python/destiny/test/ballpark/test_visibility.py" => [
        "test_returns_zero_when_there_is_no_occlusion",
        "test_returns_the_id_of_the_occluding_ball_when_there_is_an_occlusion",
        "test_ball_that_is_not_massive_is_not_an_occlusion",
        "test_ball_that_is_cloaked_is_not_an_occlusion","test_cloaked_balls_are_cloaked",
        "test_cloaked_balls_are_not_massive","test_uncloaked_balls_are_not_cloaked",
        "test_uncloaking_makes_a_ball_massive",
        "test_uncloaking_a_ball_in_warp_does_not_make_it_massive",
        "test_scan_cone_finds_nothing_when_there_is_nothing_to_be_found",
        "test_scan_cone_finds_ball_when_it_is_in_the_cone",
        "test_scan_cone_excludes_balls_not_in_cone",
    ]),
    file!("python/destiny/test/net/client/test_mergestateintohistory.py" => [
        "test_merging_empty_state_list_has_no_effect",
        "test_merging_empty_state_list_with_wait_for_bubble",
        "test_merging_empty_state_list_without_wait_for_bubble",
        "test_merge_two_states_same_tick_wait_for_bubble_should_clear",
        "test_merge_two_states_same_tick_wait_for_bubble_should_clear_if_wait_in_second_state",
        "test_merge_two_states_same_tick_no_wait_for_bubble",
        "test_merge_newer_state_wait_for_bubble_persists_for_older_state",
        "test_merge_newer_state_wait_for_bubble_persists_for_newer_state",
        "test_merge_older_state","test_merge_older_state_older_wait_for_bubble",
        "test_merge_older_state_newer_wait_for_bubble",
    ]),
    file!("python/destiny/test/net/client/test_ticker.py" => [
        "test_setstate","test_stopball","test_future_state_gets_applied_at_correct_time",
        "test_late_arrival","test_synchronize_to_simulation_time_can_not_rewind_before_first_tick",
        "test_synchronize_to_simulation_time_can_rewind_to_last_tick",
        "test_synchronize_to_simulation_time_can_rewind_two_ticks",
        "test_no_desync_reported_for_successfuly_handled_update",
        "test_fatal_desync_reported_when_update_has_multiple_timestamps",
        "test_recoverable_desync_reported_when_fail_to_sync_to_timestamp",
    ]),
    file!("python/destiny/test/net/server/test_actions.py" => [
        "test_go_to_point","test_duplicate_subsequent_actions_are_ignored",
        "test_duplicate_subsequent_actions_with_different_timestamps_are_not_ignored",
        "test_duplicate_non_subsequent_actions_are_not_ignored","test_go_to_direction","test_orbit",
        "test_set_ball_troll","test_set_ball_velocity","test_set_ball_angular_velocity",
        "test_set_ball_angular_velocity_raises_when_dynamical_orientation_disabled",
        "test_set_max_angular_velocity",
        "test_set_max_angular_velocity_raises_when_dynamical_orientation_disabled",
        "test_set_ball_rotation","test_set_ball_rotation_raises_when_dynamical_orientation_disabled",
        "test_set_ball_massive","test_stop","test_set_ball_mass","test_set_ball_agility",
        "test_set_ball_angular_agility",
        "test_set_ball_angular_agility_raises_when_dynamical_orientation_disabled",
        "test_add_ball_to_client_parks","test_make_ball_local","test_make_ball_global_makes_ball_global",
        "test_make_ball_global_adds_ball_to_client_parks",
        "test_make_ball_global_sends_out_signal_with_src_id",
        "test_remove_ball_removes_ball_right_away",
        "test_remove_ball_does_not_note_removal_of_non_global_ball",
        "test_remove_ball_notifies_removal_of_global_ball","test_set_speed_fraction","test_warp_to",
        "test_entity_warp_in","test_set_ball_position_local_ball",
        "test_set_ball_position_not_local_ball",
        "test_set_ball_harmonic_on_forcefield_with_all_negative_one_values_makes_field_non_massive",
        "test_set_ball_harmonic_on_forcefield_with_harmonic_value_makes_field_massive",
        "test_set_ball_harmonic_on_forcefield_with_corporation_id_makes_field_massive",
        "test_set_ball_harmonic_on_forcefield_with_alliance_id_makes_field_massive",
        "test_set_ball_harmonic_on_forcefield_sets_harmonic_values",
        "test_set_ball_harmonic_on_non_forcefield_sets_harmonic_values","test_set_ball_radius",
        "test_set_ball_free","test_set_ball_not_free","test_set_ball_interactive",
        "test_set_ball_not_interactive","test_follow_ball","test_set_max_speed",
        "test_set_max_angular_speed",
        "test_set_ball_angular_speed_raises_when_dynamical_orientation_disabled",
        "test_cloak_nonexistent_ball_should_fail","test_cloak_existing_ball","test_uncloak_ball",
        "test_launch_missile","test_clean_up_followers","test_undo_pending_cloak",
        "test_undo_pending_cloak_ignores_other_balls","test_undo_pending_cloak_ignores_other_actions",
        "test_has_pending_cloak_returns_false_when_no_pending_cloak",
        "test_has_pending_cloak_returns_true_when_pending_cloak",
        "test_has_pending_uncloak_returns_false_when_no_pending_uncloak",
        "test_has_pending_uncloak_returns_true_when_pending_uncloak",
        "test_get_pending_cloak_mode_returns_none_when_ball_does_not_exist",
        "test_get_pending_cloak_mode_returns_existing_mode_when_no_cloak_pending",
        "test_get_pending_cloak_mode_returns_pending_cloak_mode_when_no_cloak_pending",
        "test_has_pending_set_free_returns_false_when_freedom_not_pending",
        "test_has_pending_set_free_returns_false_when_freedom_not_pending_and_ball_already_free",
        "test_has_pending_set_free_returns_true_when_freedom_pending",
        "test_has_pending_set_not_free_returns_false_when_freedom_removal_not_pending",
        "test_has_pending_set_not_free_returns_false_when_freedom_removal_not_pending_and_ball_already_not_free",
        "test_has_pending_set_not_free_returns_true_when_freedom_removal_pending",
        "test_get_pending_interactive_state_returns_none_when_ball_does_not_exist",
        "test_get_pending_interactive_state_returns_current_state_when_ball_exists",
        "test_get_pending_interactive_state_returns_pending_state_when_available",
        "test_get_pending_speed_fraction_returns_none_when_ball_does_not_exist",
        "test_get_pending_speed_fraction_returns_current_state_when_ball_exists",
        "test_get_pending_speed_fraction_returns_pending_state_when_available",
    ]),
    file!("python/destiny/test/net/server/test_bubbleupdater.py" => [
        "test_additions_and_deletions","test_additions_and_deletions_updates_bubbles_dict",
        "test_additions_and_deletions_handles_removal",
        "test_additions_and_deletions_multiple_calls_same_tick",
    ]),
    file!("python/destiny/test/net/server/test_ticker.py" => [
        "test_applies_action","test_cloak_ball_cloaks_ball","test_cloak_ball_emits_signal",
        "test_cloak_ball_event_narrowcast_to_clients_in_bubble",
        "test_cloaking_and_uncloaking_in_same_tick_does_not_uncloak_ball",
        "test_uncloak_ball_uncloaks_ball","test_uncloak_does_not_error_when_ball_missing",
        "test_uncloak_ball_emits_signal","test_uncloak_event_sent_to_uncloaking_ball",
        "test_add_ball_event_sent_to_balls_in_same_bubble_as_uncloaking_ball",
        "test_set_ball_position_emits_signal","test_set_ball_position_sets_ball_position",
        "test_set_ball_position_event_sent_to_bubble",
        "test_set_ball_position_event_not_sent_to_bubble_for_local_balls",
        "test_add_balls_to_park","test_ball_not_global_sends_remove_ball_update_to_other_bubbles",
        "test_handle_remove_global_ball_sends_remove_ball_event_to_each_bubble_containing_interactives",
        "test_cloaked_ball_updates_only_get_sent_to_cloaked_balls_client",
        "test_no_updates_are_sent_out_for_bubbles_not_containing_interactive_balls",
    ]),
    file!("python/destiny/test/net/server/test_updatebatcher.py" => [
        "test_add_to_character_history","test_add_to_character_history_adds_to_back",
        "test_add_to_character_history_can_insert_in_front","test_clear_character_history",
        "test_add_to_bubble_history","test_character_history_only_has_cast_count_one",
        "test_clients_with_character_history_are_returned_as_a_set",
        "test_bubble_history_only_has_cast_count_one",
        "test_character_and_bubble_history_has_cast_count_two","test_send_full_state_update",
        "test_update_bubbles_inserts_add_balls_actions_to_character_history",
        "test_update_bubbles_inserts_remove_balls_actions_to_character_history",
        "test_character_has_history","test_bubble_has_history",
    ]),
    file!("python/destiny/test/test_ball.py" => [
        "test_can_construct","test_can_add_miniball","test_can_add_minicapsule",
        "test_can_not_add_minicapsule_with_negative_radius",
        "test_get_rotated_vector_returns_original_vector_if_there_is_no_rotation",
        "test_add_proximity_sensor",
        "test_reserve_formation_slot_returns_negative_one_when_ball_is_not_set_up_properly",
        "test_reserve_formation_slot","test_slots_are_reserved_in_incremental_order",
        "test_reserving_too_many_formation_slots_fails","test_free_formation_slot",
        "test_default_values",
    ]),
    file!("python/destiny/test/test_cleanup.py" => [
        "test_initial_count_is_zero","test_parks_get_counted","test_balls_get_counted",
        "test_miniballs_get_counted","test_miniboxes_get_counted","test_minicapsules_get_counted",
        "test_clear_all_resets_counts","test_clientballs_get_counted","test_clientballs_get_cleared",
    ]),
    file!("python/destiny/test/test_configure.py" => [
        "test_initial_settings_configuration_values_match_default_values","test_configure",
        "test_reset","test_enable_dynamical_orientation",
        "test_disable_dynamical_orientation_for_missiles","test_enable_new_orbit",
    ]),
    file!("python/destiny/test/test_using_correct_module.py" => [
        "test_using_destiny_from_carbon_module","test_destiny_python_module_is_in_path",
    ]),
    file!("tests/TestAABB.cpp" => [
        "DefaultConstructor","ConstructorWithParameters","High","Low","HighIgnore","LowIgnore",
        "ExcludeReturnsFalseWhenRadiusIntersects","ExcludeLeft","ExcludeRight","ExcludeTop",
        "ExcludeBottom","ExcludeFront","ExcludeBack","InsideBox","ZeroSize","XAxisIsLongest",
        "YAxisIsLongest","ZAxisIsLongest",
    ]),
    file!("tests/TestBoxShape.cpp" => [
        "CanCreate","GetClosestCornerToPointTopRightBack","GetClosestCornerToPointTopRightFront",
        "GetCenter","GetBoundingRadius","CanCreate","CenterOfRectangle","GrazeLeftSide",
        "GrazeRightSide","GrazeTopSide","GrazeBottomSide","FrontCenter","BackCenter","LeftCenter",
        "RightCenter","TopCenter","BottomCenter","CenterOfBox","TopFrontRightCorner","Left","Right",
        "Top","Bottom","Back","Front",
    ]),
    file!("tests/TestCollision.cpp" => [
        "ArbitraryPoint","IntersectionExists","NoIntersection","ParallelLineSegment","HeadOn",
        "FromInside","CompleteMiss","CenterOfSphereIntersectsTriangle","SphereGrazesTriangleEdge",
        "CenterOfSphereIntersectsTriangleFromTheWrongSide","SphereDoesNotIntersectPlane",
        "SphereDoesNotIntersectTriangle",
    ]),
    file!("tests/TestPlane.cpp" => ["CanCreate"]),
    file!("tests/TestTriangle.cpp" => [
        "CanCreate","GetNormal","CenterOfTriangle","OutsideAB","OutsideAC","OutsideBC",
        "PointAboveTriangle","PointBelowTriangle","PointLeftOfTriangle","PointBottomOfTriangle",
        "PointRightOfTriangle","PointTopOfTriangle","PointOffTheLongSide",
    ]),
    file!("tests/TestVector3d.cpp" => [
        "InitializesToZero","Subtraction","ParallelVectors","OrthogonalVectors",
    ]),
];
