#!/usr/bin/env python3
"""Generate the portable compatibility registry from the audited title inventory."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def compact_record(record: dict) -> dict:
    source = record.get("source", {})
    differences = record.get("equivalence_analysis", {}).get("material_differences", "")
    if not differences:
        differences = record.get("mapping_review", {}).get("material_difference", "")
    return {
        "title_id": record["title_id"],
        "canonical_title": record["canonical_title"],
        "name": record["name"],
        "item_kind": record["item_kind"],
        "api_surface": record.get("api_surface", ""),
        "category": record["classification"]["category"],
        "verdict": record["verdict"],
        "material_difference": differences,
        "mapping_explanation": record.get("mapping_explanation", ""),
        "mapping_items": [
            {
                "api_title": item["api_title"],
                "ecosystem": item["ecosystem"],
                "version": item["version"],
                "material_difference": item.get("material_difference", ""),
            }
            for item in record.get("mapping_items", [])
        ],
        "source": {
            "repository": source.get("repository", ""),
            "commit": source.get("commit", ""),
            "path": source.get("path", ""),
            "start_line": source.get("start_line"),
            "end_line": source.get("end_line"),
        },
    }


def rust_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def generate(source_path: Path) -> None:
    source = json.loads(source_path.read_text(encoding="utf-8"))
    records = [compact_record(record) for record in source["records"]]
    payload = {
        "schema_version": 1,
        "source_schema_version": source.get("schema_version"),
        "source_baseline": source.get("baseline"),
        "records": records,
    }

    registry_dir = ROOT / "registry"
    python_dir = ROOT / "python" / "destiny"
    source_dir = ROOT / "src"
    registry_dir.mkdir(parents=True, exist_ok=True)
    python_dir.mkdir(parents=True, exist_ok=True)
    source_dir.mkdir(parents=True, exist_ok=True)

    compact_json = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    (registry_dir / "title_mapping.json").write_text(compact_json, encoding="utf-8")

    python_payload = json.dumps(records, ensure_ascii=False, separators=(",", ":"))
    python_source = (
        '"""Generated Destiny-to-Bevy title registry. Do not edit by hand."""\n\n'
        "from __future__ import annotations\n\n"
        "import json as _json\n"
        "from types import MappingProxyType as _MappingProxyType\n\n"
        f"_ROWS = _json.loads({python_payload!r})\n"
        "def _deep_freeze(value):\n"
        "    if isinstance(value, dict):\n"
        "        return _MappingProxyType({key: _deep_freeze(item) for key, item in value.items()})\n"
        "    if isinstance(value, list):\n"
        "        return tuple(_deep_freeze(item) for item in value)\n"
        "    return value\n\n"
        "RECORDS = _MappingProxyType({row['canonical_title']: _deep_freeze(row) for row in _ROWS})\n"
        "del _ROWS\n"
    )
    (python_dir / "_registry.py").write_text(python_source, encoding="utf-8")

    rust_lines = [
        "// Generated by tools/generate_registry.py. Do not edit by hand.",
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
        "pub struct GeneratedTitleRecord {",
        "    pub canonical_title: &'static str,",
        "    pub verdict: &'static str,",
        "    pub material_difference: &'static str,",
        "    pub mapping_items: &'static [&'static str],",
        "}",
        "",
        "pub const GENERATED_TITLE_RECORDS: &[GeneratedTitleRecord] = &[",
    ]
    for record in records:
        rust_lines.append(
            "    GeneratedTitleRecord { canonical_title: %s, verdict: %s, material_difference: %s, mapping_items: &[%s] },"
            % (
                rust_string(record["canonical_title"]),
                rust_string(record["verdict"]),
                rust_string(record["material_difference"]),
                ", ".join(rust_string(item["api_title"]) for item in record["mapping_items"]),
            )
        )
    rust_lines.extend(["];", ""])
    (source_dir / "generated_registry.rs").write_text("\n".join(rust_lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path, help="Path to title_inventory.json")
    args = parser.parse_args()
    generate(args.input.resolve())


if __name__ == "__main__":
    main()
